.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "DC\-CLI" "1" "August 2020" "" ""
.
.SH "NAME"
\fBdc\-cli\fR \- (Amplience) Dynamic Content command line interface
.
.SH "SYNOPSIS"
\fBdc\-cli\fR \fB<command>\fR \fB[args]\fR
.
.SH "DESCRIPTION"
\fBdc\-cli\fR is a command line interface application for Amplience Dynamic Content management APIs\.
.
.P
Run \fBdc\-cli\fR to get a list of available commands
.
.SH "CONFIGURATION"
\fBdc\-cli\fR requires a valid set of Amplience client credentials (\fB\-\-clientId\fR & \fB\-\-clientSecret\fR) and hub ID (\fB\-\-hubId\fR) to operate\. These must be supplied for each command or alternatively they can saved to a user\-level configuration file using \fBdc\-cli configure\fR\.
.
.P
By default the configuration file is saved into the directory \fB<HOME_DIR>/\.amplience/\fR, this can be overridden using the \fB\-\-config\fR option\.
.
.P
See \fBdc\-cli configure \-\-help\fR for more information\.
.
.SH "SEE ALSO"
.
.IP "\(bu" 4
\fBdc\-cli \-\-help\fR
.
.IP "\(bu" 4
\fBdc\-cli <command> \-\-help\fR
.
.IP "\(bu" 4
\fBREADME\.md\fR
.
.IP "\(bu" 4
https://docs\.amplience\.net/
.
.IP "" 0

