name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [20, 22, 24]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}

      - name: npm install, build, and test
        run: |
          npm ci --ignore-scripts
          npm run build --if-present
          npm test
        env:
          CI: true
