name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 10.16.1

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm
          registry-url: https://npm.pkg.github.com

      - name: pnpm install, build, and test
        run: |
          pnpm install --frozen-lockfile
          pnpm run build
          pnpm test
        env:
          CI: true
